CONFEDERATIONS: dict[str, str] = {
    "Albania": "UEFA", "Algeria": "CAF", "Argentina": "CONMEBOL",
    "Australia": "AFC", "Austria": "UEFA", "Belgium": "UEFA",
    "Bolivia": "CONMEBOL", "Bosnia and Herzegovina": "UEFA",
    "Brazil": "CONMEBOL", "Cameroon": "CAF",
    "Canada": "CONCACAF", "Cape Verde": "CAF",
    "Chile": "CONMEBOL", "Colombia": "CONMEBOL",
    "Congo DR": "CAF", "Costa Rica": "CONCACAF", "Croatia": "UEFA",
    "Curaçao": "CONCACAF", "Czech Republic": "UEFA",
    "Denmark": "UEFA", "DR Congo": "CAF",
    "Ecuador": "CONMEBOL", "Egypt": "CAF",
    "England": "UEFA", "Finland": "UEFA", "France": "UEFA",
    "Germany": "UEFA", "Ghana": "CAF", "Greece": "UEFA",
    "Haiti": "CONCACAF", "Honduras": "CONCACAF", "Hungary": "UEFA",
    "Indonesia": "AFC", "Iran": "AFC", "Iraq": "AFC",
    "Israel": "UEFA", "Italy": "UEFA", "Ivory Coast": "CAF",
    "Jamaica": "CONCACAF", "Japan": "AFC", "Jordan": "AFC",
    "Kenya": "CAF",
    "Korea Republic": "AFC", "South Korea": "AFC",
    "Mali": "CAF", "Mexico": "CONCACAF", "Morocco": "CAF",
    "Netherlands": "UEFA", "New Zealand": "OFC",
    "Nigeria": "CAF", "Norway": "UEFA",
    "Panama": "CONCACAF", "Paraguay": "CONMEBOL", "Peru": "CONMEBOL",
    "Poland": "UEFA", "Portugal": "UEFA",
    "Qatar": "AFC",
    "Romania": "UEFA",
    "Saudi Arabia": "AFC", "Scotland": "UEFA",
    "Senegal": "CAF", "Serbia": "UEFA", "Slovakia": "UEFA",
    "Slovenia": "UEFA", "South Africa": "CAF", "Spain": "UEFA",
    "Sweden": "UEFA", "Switzerland": "UEFA",
    "Thailand": "AFC", "Trinidad and Tobago": "CONCACAF",
    "Tunisia": "CAF", "Turkey": "UEFA", "Türkiye": "UEFA",
    "Uganda": "CAF", "Ukraine": "UEFA",
    "United States": "CONCACAF", "USA": "CONCACAF",
    "Uruguay": "CONMEBOL", "Uzbekistan": "AFC",
    "Venezuela": "CONMEBOL", "Vietnam": "AFC",
    "Wales": "UEFA",
}


def get_confederation(team_name: str) -> str:
    return CONFEDERATIONS.get(team_name, "UNKNOWN")
